### ISSUE TITLE
comment specification error

### ISSUE THREAD

**Issue by RocketPop** [groksrc/ruby_colors_for_vscode#1]
Hi - sorry for no Pull Request but the contents of ruby.configuration.json should be as follows:

`
{
    "comments": {
        "lineComment": "#",
        "blockComment": [ "=begin", "=end" ]
    },
    "brackets": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"]
    ]
}
`

**Comment by groksrc** [comment]
Thanks for letting me know, I'd been meaning to get to that. Now fixed in v0.0.6. :+1:
