### ISSUE TITLE
An attempt to merge this extension with vscode-ruby

### ISSUE THREAD

**Issue by lextm** [groksrc/ruby_colors_for_vscode#2]
vscode-ruby is another Ruby extension for VS Code, which features debugger integration.

I think it would be beneficial to users if the two extensions merge together. So I made a pull request there,

https://github.com/rubyide/vscode-ruby/pull/23

**Comment by groksrc** [comment]
Agree, I will leave this up for posterity but have no further plans of advancing it. Some users may find the syntax highlighting by itself useful, but I use `vscode-ruby` for my day-to-day work.
